package dev.nhh.echo.server.dto;


import java.io.Serializable;
import java.util.UUID;

public class VoicePacket implements Serializable {

    private UUID channelId; //-1 means from client to util, otherwise chId generated by the util
    private UUID userId;
    private long timestamp, //-1 means from client to util, otherwise timeStamp of the moment when the util receives the message
            ttl=2000; //2 seconds TTL

    private byte[] data; //can carry any type of object. in this program, i used a sound packet, but it could be a string, a chunk of video, ...


    public VoicePacket(UUID channelId, UUID userId, long timestamp, byte[] data) {
        this.userId = userId;
        this.channelId = channelId;
        this.timestamp = timestamp;
        this.data = data;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public UUID getChannelId() {
        return channelId;
    }

    public byte[] getData() {
        return data;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public long getTtl() {
        return ttl;
    }
    public void setTtl(long ttl) {
        this.ttl = ttl;
    }

    public void setChannelId(UUID chId) {
        this.channelId = chId;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }
}
